import Head from "next/head";
import { useEffect, useState } from "react";
import Articles from "../components/Articles";
import Choose from "../components/Choose";
import Footer from "../components/Footer";
import Hero from "../components/Hero";
import Navbar from "../components/Navbar";

export default function Home() {
  return (
    <>
      <Head>
        <title>Easybank - Landing page</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta
          name="description"
          content="Generated by create next app from frontend mentor and coded by joehsn"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar />
        <Hero />
        <Choose />
        <Articles />
        <Footer />
        <div className="author">
          Coded by{" "}
          <a href="https://linktr.ee/joehsn" target="_blank" rel="noreferrer">
            @joehsn
          </a>
          .
        </div>
      </main>
    </>
  );
}
